### ISSUE TITLE
Crashes with the following pdf file

### ISSUE THREAD

**Issue by hsauro** [jalios/pdf2svg-windows#2]
pdf2svg crashes (APPCRASH) with the attached file (Using Windows 7, executing from command line: pdf2svg.exe picture.pdf picture.svg all

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	pdf2svg.exe
  Application Version:	0.0.0.0
  Application Timestamp:	557fec05
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.18933
  Fault Module Timestamp:	55a69ec4
  Exception Code:	c06d007e
  Exception Offset:	0000c42d
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

https://drive.google.com/open?id=0B-hNuhMD_P6uTVF0RzBLYU1ZUTA

**Comment by OlivierJaquemet** [comment]
Hello @hsauro,

Thanks for your participation, however, as stated on the main page of the project, **This build is provided AS IS and JALIOS SA will not do any support about that**. We forked the project to provide Windows 32&64 builds, but we do not maintain the pdf2svg code.

If you encounter any issue you should report them to the original project page : https://github.com/db9052/pdf2svg
