### ISSUE TITLE
Windows explorer freezes after trying to run pdf2svg.exe

### ISSUE THREAD

**Issue by leonardo-menjivar** [jalios/pdf2svg-windows#3]
I tried to run pdf2svg.exe (both 64 and 32 bit versions) in windows 10 home(OS Build 14393.222) but windows explorer freezes and nothing else happens. I waited for 10 minutes for it to respond but it didn't happend.
My computer is an Acer Aspire S3 i3-2367M with 4GB RAM, 64-bit operating system.

**Comment by castorls** [comment]
This project is provided 'as is' and is not maintained by our company. 

But we are open to look at any pull request you may provide about this problem.
